---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for maas_install

#Install Canonical Metal as a Service (MAAS) on Ubuntu via snap with the specific channel
- name: Install Canonical Metal as a Service (MAAS) on Ubuntu via snap with the specific channel
  community.general.snap:
    name: maas
    channel: "{{ maas_channel }}"
    classic: yes
