---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for lxd_init_preseed

# Load (preseed) the lxd init configuration
# equivalent to lxd init --preseed < /tmp/lxdconfig.yml

- block:
  - name: Set the filepath to load backup from if not specified
    pause:
      prompt: 'Enter the filepath'
    register: filepath_prompt
  
  - set_fact:
      filepath: "{{ filepath_prompt.user_input }}"
  when: filepath is not defined

- name: 'Load (preseed) the lxd init configuration'
  become: true
  shell: "lxd init --preseed < {{ filepath }}"