---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for packages_lxc_lxd

#Install LXC/LXD
#https://ubuntu.com/lxd/install


# Debian/Ubuntu
- block:

  #sudo apt-get update
  - name: "APT - update"
    become: true
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 86400 #One day
    register: cache_updated

  - block:
    #sudo apt-get -y install zfsutils-linux
    - name: "Check zfsutils-linux is installed"
      apt:
        pkg:
          - zfsutils-linux
        state: latest

    - name: Check snap is started
      become: true
      ansible.builtin.service:
        name: snapd
        state: started
      register: snapd_started
    
    #snap install lxd
    - name: Install lxd via snap
      community.general.snap:
        name: lxd
        state: present
      register: snapd_installed
      when: snapd_started    

    #sudo usermod -a -G lxd username
    - name: 'Ansible user in group lxd'
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: lxd
        append: true
      when: snapd_installed
    
    when: cache_updated
  when: ansible_os_family == 'Debian'
      
