---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for lxd_exec

# LXC/LXD - Execute a command on a container/vm

- block:
  - name: Set the container (or VM) name if not specified
    pause:
      prompt: 'Enter the container (or VM) name'
    register: name_prompt
  - set_fact: 
      container_name: "{{ name_prompt.user_input }}"
  when: container_name is not defined

- block:
  - name: Set the command if not specified
    pause:
      prompt: 'Enter the command'
    register: command_prompt
  - set_fact: 
      command: "{{ command_prompt.user_input }}"
  when: command is not defined

- name: "LXC/LXD - Execute the command {{ command }} on the container/vm {{ container_name }}"
  ansible.builtin.shell:
    "lxc exec {{ container_name }} -- {{ command }}"
  register: msg

- name: LXC/LXD - Display the output
  ansible.builtin.debug:
    msg: "{{msg.stdout_lines}}"
  when: msg is defined
