---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# defaults file for lxc_start
container_args: ''
stateless:
console:

#variables
_container_args1: ''
_container_args2: ''
_container_args_final: ''